-- CreateEnum
-- This is a comment; Prisma doesn't support raw CREATE TYPE in migrations generated by Prisma CLI.-- The Prisma schema already defines the models, so we'll create the tables directly.

-- CreateTable
CREATE TABLE "qiita_sources" (
    "id" SERIAL NOT NULL,
    "name" TEXT NOT NULL,
    "tag" TEXT NOT NULL,
    "active" BOOLEAN NOT NULL DEFAULT true,
    "tags" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "maxItems" INTEGER NOT NULL DEFAULT 50,
    "lastFetchedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "qiita_sources_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "qiita_items" (
    "id" TEXT NOT NULL,
    "sourceId" INTEGER NOT NULL,
    "title" TEXT NOT NULL,
    "body" TEXT,
    "url" TEXT NOT NULL,
    "userId" TEXT,
    "userName" TEXT,
    "likesCount" INTEGER NOT NULL DEFAULT 0,
    "stocksCount" INTEGER NOT NULL DEFAULT 0,
    "commentsCount" INTEGER NOT NULL DEFAULT 0,
    "tags" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "publishedAt" TIMESTAMP(3),
    "fetchedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "qiita_items_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "qiita_sources_tag_key" ON "qiita_sources"("tag");

-- CreateIndex
CREATE INDEX "qiita_items_sourceId_idx" ON "qiita_items"("sourceId");

-- AddForeignKey
ALTER TABLE "qiita_items" ADD CONSTRAINT "qiita_items_sourceId_fkey" FOREIGN KEY ("sourceId") REFERENCES "qiita_sources"("id") ON DELETE CASCADE ON UPDATE CASCADE;